### PR TITLE
* Add pt_BR translation

### PR DESCRIPTION
**Pull request by leleobhz**
Hello!

I appreciate a lot you sent me the files via email, but since i saw this repository exists, i think its better to fork-pull.

Some strings are marked as TODO because it is context dependent, so its hard to check if its the best translation or not. Since a first version with this got launched, i'll fix what is missing/wrong.

Chers!

### CODE REVIEW

**Comment by jasminb** [comment]
Please translate following strings and append them to already translated values in strings.xml

 <string name="misc_edit">Edit</string>
  <string name="settings_show_root">Show device root</string>
  <string name="misc_storage_details">Storage details</string>
  <string name="misc_no_compatible_app">No compatible application found to edit selected document type</string>
  <string name="sync_uploaded_count">Uploaded %s</string>
  <string name="sync_downloaded_count">Downloaded %s</string>
  <string name="misc_file">file</string>
  <string name="misc_files">files</string>

**Comment by jasminb** [comment]
Hello, please translate following values also and append them to strings.xml:


```
  <string name="misc_edit">Edit</string>
  <string name="settings_show_root">Show device root</string>
  <string name="misc_storage_details">Storage details</string>
  <string name="misc_no_compatible_app">No compatible application found to edit selected document type</string>
  <string name="sync_uploaded_count">Uploaded %s</string>
  <string name="sync_downloaded_count">Downloaded %s</string>
  <string name="misc_file">file</string>
  <string name="misc_files">files</string>
```

**Comment by leleobhz** [comment]
Hello Jasmin,

Well done!

Thanks!

**Comment by leleobhz** [comment]
Jasmin,

The string "Decryption in progress" have no entry in XML. Also, im fixing all translations marked as TODO and will make a new pull request.

Cheers!

**Pull request merged**
